### ISSUE TITLE
Status? 

### ISSUE THREAD

**Issue by rljacobson** [kehribar/ice40helper#1]
I am interested in this design. Has there been any progress on this? Has anyone been working on a version using the Nuvoton chip discussed in the [icebreaker issue](https://github.com/icebreaker-fpga/icebreaker/issues/14)?

Do you have prototype hardware for this design that you’re able to supply?

**Comment by kehribar** [comment]
Hi,

Thanks for your interest in the project.

I've been using this hardware design for almost a year now. I ordered 10 PCBs and soldered one of them. Software wise Flash and SRAM programming is working. SPI register write / read is working. So it is fair to say that fundamentals of the project is solid at the moment.

There is slight mistake in the PCB silkscreen about pin labels. Right now, they don't match with the icestorm / nextpnr toolchain pin numbering scheme. It is an easy fix for a next update but I get away with it for now. Apart from that hardware is OK too.

But,

I don't have any plans at the moment for a prototype run of this board. You can order PCBs with the supplied gerber (https://github.com/kehribar/ice40helper/tree/master/hardware/up5k_v0/gerbers) files if you want.

**Comment by rljacobson** [comment]
Thanks, @kehribar !

Is v2.0 of the iCEBreaker board still in development? I am just curious, as the iCEBreaker GitHub repo hasn't been updated in awhile. 

Thanks for sharing your work!

**Comment by kehribar** [comment]
Hi,

I'm not even remotely connected with the iCEBreaker team, so I can't comment on anything :) 

If you don't have any more things to ask about this specific project / design, I'm closing the issue. 

Thanks for your interest again.
